-- NIVELES
INSERT INTO [dbo].[NIVEL] ([COD_NIVEL] ,[NIVEL]) VALUES ('NIVEL1' ,1);
INSERT INTO [dbo].[NIVEL] ([COD_NIVEL] ,[NIVEL]) VALUES ('NIVEL2' ,2);

--CARGOS
INSERT INTO [dbo].[CARGO]([IDNIVEL] ,[CODCARGO] ,[NOMCARGO]) VALUES (1 ,'CARGO1' ,'DIRECTOR ADMINISTRATIVO');
INSERT INTO [dbo].[CARGO]([IDNIVEL] ,[CODCARGO] ,[NOMCARGO]) VALUES (1 ,'CARGO2' ,'DIRECTOR DE RRHH');
INSERT INTO [dbo].[CARGO]([IDNIVEL] ,[CODCARGO] ,[NOMCARGO]) VALUES (1 ,'CARGO3' ,'LIDER ADMINSTRATIVO');
INSERT INTO [dbo].[CARGO]([IDNIVEL] ,[CODCARGO] ,[NOMCARGO]) VALUES (2 ,'CARGO4' ,'ESPECIALISTA ADMINISTRATIVO');
INSERT INTO [dbo].[CARGO]([IDNIVEL] ,[CODCARGO] ,[NOMCARGO]) VALUES (2 ,'CARGO5' ,'ASISTENTE ADMINISTRATIVO');
INSERT INTO [dbo].[CARGO]([IDNIVEL] ,[CODCARGO] ,[NOMCARGO]) VALUES (2 ,'CARGO6' ,'CHOFER');