//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGVIDAPS_DAT
{
    using System;
    using System.Collections.Generic;
    
    public partial class CALCULO
    {
        public CALCULO()
        {
            this.DETALLE_CALCULO = new HashSet<DETALLE_CALCULO>();
        }
    
        public decimal IDCALCULO { get; set; }
        public Nullable<decimal> IDSOLICANT { get; set; }
    
        public virtual FORMULARIO__ANTICIPO FORMULARIO__ANTICIPO { get; set; }
        public virtual ICollection<DETALLE_CALCULO> DETALLE_CALCULO { get; set; }
    }
}
