//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGVIDAPS_DAT
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARGO
    {
        public CARGO()
        {
            this.EMPLEADOes = new HashSet<EMPLEADO>();
        }
    
        public decimal IDCARGO { get; set; }
        public Nullable<decimal> IDNIVEL { get; set; }
        public string CODCARGO { get; set; }
        public string NOMCARGO { get; set; }
    
        public virtual NIVEL NIVEL { get; set; }
        public virtual ICollection<EMPLEADO> EMPLEADOes { get; set; }
    }
}
