//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGVIDAPS_DAT
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_FORMULARIO
    {
        public decimal IDDETFORM { get; set; }
        public Nullable<decimal> IDFORMANTICIPO { get; set; }
        public Nullable<decimal> IDFORMLIQ { get; set; }
        public Nullable<decimal> IDTIPOTRANSPORTE { get; set; }
        public Nullable<decimal> IDRUTA { get; set; }
        public string NOMBRETRANSPORTE { get; set; }
        public Nullable<System.DateTime> SALIDATRANSPORTE { get; set; }
        public Nullable<System.DateTime> LLEGADATRANSPORTE { get; set; }
    
        public virtual FORMULARIO__ANTICIPO FORMULARIO__ANTICIPO { get; set; }
        public virtual FORMULARIO_LIQUIDACION FORMULARIO_LIQUIDACION { get; set; }
        public virtual RUTA RUTA { get; set; }
        public virtual TIPO_TRANSPORTE TIPO_TRANSPORTE { get; set; }
    }
}
