//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGVIDAPS_DAT
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_FORMULARIO
    {
        public decimal IDDETFORM { get; set; }
        public Nullable<decimal> IDFORMANTICIPO { get; set; }
        public Nullable<decimal> IDFORMLIQ { get; set; }
        public Nullable<decimal> IDTIPOTRANSPORTE { get; set; }
        public Nullable<decimal> IDRUTA { get; set; }
        public string NOMBRETRANSPORTE { get; set; }
        public Nullable<System.DateTime> SALIDATRANSPORTE { get; set; }
        public Nullable<System.DateTime> LLEGADATRANSPORTE { get; set; }
        public Nullable<decimal> MONTOTRANSPORTE { get; set; }
    
        public virtual FORMULARIO__ANTICIPO FORMULARIO__ANTICIPO { get; set; }
        public virtual FORMULARIO_LIQUIDACION FORMULARIO_LIQUIDACION { get; set; }
        public virtual RUTA RUTA { get; set; }
        public virtual TIPO_TRANSPORTE TIPO_TRANSPORTE { get; set; }
    }
}
