//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGVIDAPS_DAT
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_CALCULO
    {
        public decimal IDDETALLECALCULO { get; set; }
        public Nullable<decimal> IDCALCULO { get; set; }
        public Nullable<decimal> IDOPCIONN { get; set; }
        public Nullable<decimal> SUBTOTALMONTO { get; set; }
    
        public virtual CALCULO CALCULO { get; set; }
        public virtual OPCION_NIVEL OPCION_NIVEL { get; set; }
    }
}
