//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGVIDAPS_DAT
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_FORMULARIO
    {
        public decimal IDDETSOLIC { get; set; }
        public Nullable<decimal> IDSOLICANT { get; set; }
        public Nullable<decimal> IDSOLICLIQ { get; set; }
        public Nullable<decimal> IDTIPOTRANSPORTE { get; set; }
        public Nullable<decimal> IDRUTA { get; set; }
        public Nullable<System.DateTime> FECSALIDA { get; set; }
        public Nullable<int> HORASALIDA { get; set; }
        public Nullable<System.DateTime> FECLLEGADA { get; set; }
        public Nullable<int> HORALLEGADA { get; set; }
    
        public virtual FORMULARIO__ANTICIPO FORMULARIO__ANTICIPO { get; set; }
        public virtual FORMULARIO_LIQUIDACION FORMULARIO_LIQUIDACION { get; set; }
        public virtual RUTA RUTA { get; set; }
        public virtual TIPO_TRANSPORTE TIPO_TRANSPORTE { get; set; }
    }
}
