//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGVIDAPS_DAT
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADO
    {
        public EMPLEADO()
        {
            this.FORMULARIO__ANTICIPO = new HashSet<FORMULARIO__ANTICIPO>();
            this.USUARIOs = new HashSet<USUARIO>();
        }
    
        public decimal IDEMP { get; set; }
        public Nullable<decimal> IDCARGO { get; set; }
        public string CEDULAEMP { get; set; }
        public string NOMBREEMP { get; set; }
        public string APELLIDOEMP { get; set; }
        public string DIREMP { get; set; }
        public string TELEMP { get; set; }
        public Nullable<bool> ESTEMP { get; set; }
    
        public virtual CARGO CARGO { get; set; }
        public virtual ICollection<FORMULARIO__ANTICIPO> FORMULARIO__ANTICIPO { get; set; }
        public virtual ICollection<USUARIO> USUARIOs { get; set; }
    }
}
