//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGVIDAPS_DAT
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTADO_SOLICITUD_ANTICIPO
    {
        public ESTADO_SOLICITUD_ANTICIPO()
        {
            this.FORMULARIO__ANTICIPO = new HashSet<FORMULARIO__ANTICIPO>();
        }
    
        public decimal IDESTSOLICANT { get; set; }
        public string ESTSOLICANT { get; set; }
    
        public virtual ICollection<FORMULARIO__ANTICIPO> FORMULARIO__ANTICIPO { get; set; }
    }
}
