//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGVIDAPS_DAT
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURA
    {
        public decimal IDFACTURA { get; set; }
        public Nullable<decimal> IDFORMLIQ { get; set; }
        public string PATHIMAGENFAC { get; set; }
        public Nullable<decimal> MONTOFAC { get; set; }
    
        public virtual FORMULARIO_LIQUIDACION FORMULARIO_LIQUIDACION { get; set; }
    }
}
