//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGVIDAPS_DAT
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORMULARIO__ANTICIPO
    {
        public FORMULARIO__ANTICIPO()
        {
            this.CALCULOes = new HashSet<CALCULO>();
            this.DETALLE_FORMULARIO = new HashSet<DETALLE_FORMULARIO>();
        }
    
        public decimal IDFORMANTICIPO { get; set; }
        public Nullable<decimal> IDCOMBINACION { get; set; }
        public Nullable<decimal> IDEMP { get; set; }
        public string NUMFORMANTICIPO { get; set; }
        public Nullable<System.DateTime> FECFORMANTICIPO { get; set; }
        public string CIUDADFORMANTICIPO { get; set; }
        public string UNIDADFORMANTICIPO { get; set; }
        public Nullable<System.DateTime> SALIDAFORMANTICIPO { get; set; }
        public Nullable<System.DateTime> LLEGADAFORMANTICIPO { get; set; }
        public string DESCRIPCIONFORMANTICIPO { get; set; }
        public string BANCOFORMANTICIPO { get; set; }
        public string TIPOCUENTAFORMANTICIPO { get; set; }
        public string NUMCUENTAFORMANTICIPO { get; set; }
        public string ESTADOFORMANTICIPO { get; set; }
        public Nullable<decimal> MONTOTOTAL { get; set; }
    
        public virtual ICollection<CALCULO> CALCULOes { get; set; }
        public virtual COMBINACION_VIATICOS COMBINACION_VIATICOS { get; set; }
        public virtual ICollection<DETALLE_FORMULARIO> DETALLE_FORMULARIO { get; set; }
        public virtual EMPLEADO EMPLEADO { get; set; }
    }
}
