//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGVIDAPS_DAT
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORMULARIO__ANTICIPO
    {
        public FORMULARIO__ANTICIPO()
        {
            this.CALCULOes = new HashSet<CALCULO>();
            this.DETALLE_FORMULARIO = new HashSet<DETALLE_FORMULARIO>();
        }
    
        public decimal IDSOLICANT { get; set; }
        public Nullable<decimal> IDESTSOLICANT { get; set; }
        public Nullable<decimal> IDCOMBINACION { get; set; }
        public Nullable<decimal> IDEMP { get; set; }
        public string CODSOLICANT { get; set; }
        public string NUMSOLICANT { get; set; }
        public Nullable<System.DateTime> FECSOLICANT { get; set; }
    
        public virtual ICollection<CALCULO> CALCULOes { get; set; }
        public virtual COMBINACION_VIATICOS COMBINACION_VIATICOS { get; set; }
        public virtual ICollection<DETALLE_FORMULARIO> DETALLE_FORMULARIO { get; set; }
        public virtual EMPLEADO EMPLEADO { get; set; }
        public virtual ESTADO_SOLICITUD_ANTICIPO ESTADO_SOLICITUD_ANTICIPO { get; set; }
    }
}
