//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGVIDAPS_DAT
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENU_PERFIL
    {
        public decimal IDMENUPERFIL { get; set; }
        public Nullable<decimal> IDPERFIL { get; set; }
        public string MENUPERFIL { get; set; }
    
        public virtual PERFIL PERFIL { get; set; }
    }
}
