//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGVIDAPS_DAT
{
    using System;
    using System.Collections.Generic;
    
    public partial class NIVEL
    {
        public NIVEL()
        {
            this.CARGOes = new HashSet<CARGO>();
            this.OPCION_NIVEL = new HashSet<OPCION_NIVEL>();
        }
    
        public decimal IDNIVEL { get; set; }
        public string COD_NIVEL { get; set; }
        public int NIVEL1 { get; set; }
    
        public virtual ICollection<CARGO> CARGOes { get; set; }
        public virtual ICollection<OPCION_NIVEL> OPCION_NIVEL { get; set; }
    }
}
