//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGVIDAPS_DAT
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPCION_NIVEL
    {
        public decimal IDOPCIONN { get; set; }
        public Nullable<decimal> IDOPCION { get; set; }
        public Nullable<decimal> IDNIVEL { get; set; }
        public string CODOPCIONN { get; set; }
        public Nullable<decimal> VALOROPCION { get; set; }
    
        public virtual NIVEL NIVEL { get; set; }
        public virtual OPCIONES_VIATICOS OPCIONES_VIATICOS { get; set; }
    }
}
