//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGVIDAPS_DAT
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPCIONES_VIATICOS
    {
        public OPCIONES_VIATICOS()
        {
            this.OPCION_NIVEL = new HashSet<OPCION_NIVEL>();
        }
    
        public decimal IDOPCION { get; set; }
        public string NOMBREOPCION { get; set; }
    
        public virtual ICollection<OPCION_NIVEL> OPCION_NIVEL { get; set; }
    }
}
