//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGVIDAPS_DAT
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPCION_NIVEL
    {
        public OPCION_NIVEL()
        {
            this.DETALLE_CALCULO = new HashSet<DETALLE_CALCULO>();
        }
    
        public decimal IDOPCIONN { get; set; }
        public Nullable<decimal> IDOPCION { get; set; }
        public Nullable<decimal> IDNIVEL { get; set; }
        public Nullable<decimal> VALOROPCION { get; set; }
    
        public virtual ICollection<DETALLE_CALCULO> DETALLE_CALCULO { get; set; }
        public virtual NIVEL NIVEL { get; set; }
        public virtual OPCIONES_VIATICOS OPCIONES_VIATICOS { get; set; }
    }
}
