//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGVIDAPS_DAT
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERFIL
    {
        public PERFIL()
        {
            this.USUARIOs = new HashSet<USUARIO>();
        }
    
        public decimal IDPERFIL { get; set; }
        public string NOMBREPERFIL { get; set; }
        public string MENUSACCESO { get; set; }
    
        public virtual ICollection<USUARIO> USUARIOs { get; set; }
    }
}
