//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGVIDAPS_DAT
{
    using System;
    using System.Collections.Generic;
    
    public partial class RUTA
    {
        public RUTA()
        {
            this.DETALLE_FORMULARIO = new HashSet<DETALLE_FORMULARIO>();
        }
    
        public decimal IDRUTA { get; set; }
        public string LUGARSALIDA { get; set; }
        public string LUGARLLEGADA { get; set; }
        public string CODRUTA { get; set; }
        public Nullable<bool> ESTRUTA { get; set; }

        public string RUTACOMPLETA
        {
            get
            {
                return LUGARSALIDA + " - " + LUGARLLEGADA;
            }
        }
    
        public virtual ICollection<DETALLE_FORMULARIO> DETALLE_FORMULARIO { get; set; }
    }
}
