//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGVIDAPS_DAT
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOLICITUD_LIQUIDACION
    {
        public SOLICITUD_LIQUIDACION()
        {
            this.DETALLE_SOLICITUD_ANTICIPO = new HashSet<DETALLE_SOLICITUD_ANTICIPO>();
            this.FACTURACIONs = new HashSet<FACTURACION>();
        }
    
        public decimal IDSOLICLIQ { get; set; }
        public string CODSOLICLIQ { get; set; }
        public string NUMSOLICLIQ { get; set; }
        public Nullable<System.DateTime> FECSOLICLIQ { get; set; }
    
        public virtual ICollection<DETALLE_SOLICITUD_ANTICIPO> DETALLE_SOLICITUD_ANTICIPO { get; set; }
        public virtual ICollection<FACTURACION> FACTURACIONs { get; set; }
    }
}
