//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGVIDAPS_DAT
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOLICITUD__ANTICIPO
    {
        public SOLICITUD__ANTICIPO()
        {
            this.CALCULOes = new HashSet<CALCULO>();
            this.DETALLE_SOLICITUD = new HashSet<DETALLE_SOLICITUD>();
        }
    
        public decimal IDSOLICANT { get; set; }
        public Nullable<decimal> IDESTSOLICANT { get; set; }
        public Nullable<decimal> IDCOMBINACION { get; set; }
        public Nullable<decimal> IDEMP { get; set; }
        public string CODSOLICANT { get; set; }
        public string NUMSOLICANT { get; set; }
        public Nullable<System.DateTime> FECSOLICANT { get; set; }
    
        public virtual ICollection<CALCULO> CALCULOes { get; set; }
        public virtual COMBINACION_VIATICOS COMBINACION_VIATICOS { get; set; }
        public virtual ICollection<DETALLE_SOLICITUD> DETALLE_SOLICITUD { get; set; }
        public virtual EMPLEADO EMPLEADO { get; set; }
        public virtual ESTADO_SOLICITUD_ANTICIPO ESTADO_SOLICITUD_ANTICIPO { get; set; }
    }
}
