//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGVIDAPS_DAT
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_TRANSPORTE
    {
        public TIPO_TRANSPORTE()
        {
            this.DETALLE_FORMULARIO = new HashSet<DETALLE_FORMULARIO>();
        }
    
        public decimal IDTIPOTRANSPORTE { get; set; }
        public string TIPOTRANSPORTE { get; set; }
    
        public virtual ICollection<DETALLE_FORMULARIO> DETALLE_FORMULARIO { get; set; }
    }
}
