//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGVIDAPS_DAT
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_CALCULO
    {
        public decimal IDDETALLECALCULO { get; set; }
        public Nullable<decimal> IDOPCION { get; set; }
        public Nullable<decimal> IDCALCULO { get; set; }
    
        public virtual CALCULO CALCULO { get; set; }
        public virtual OPCIONES_VIATICOS OPCIONES_VIATICOS { get; set; }
    }
}
