//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGVIDAPS_DAT
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_FACTURACION
    {
        public decimal IDDETALLEFAC { get; set; }
        public Nullable<decimal> IDFACTURACION { get; set; }
    
        public virtual FACTURACION FACTURACION { get; set; }
    }
}
