//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGVIDAPS_DAT
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADO
    {
        public EMPLEADO()
        {
            this.SOLICITUD__ANTICIPO = new HashSet<SOLICITUD__ANTICIPO>();
        }
    
        public decimal IDEMP { get; set; }
        public Nullable<decimal> IDCARGO { get; set; }
        public string CODEMP { get; set; }
        public string CEDULAEMP { get; set; }
        public string NOMBREEMP { get; set; }
        public string APELLIDOEMP { get; set; }
        public string DIREMP { get; set; }
        public string TELEMP { get; set; }
    
        public virtual CARGO CARGO { get; set; }
        public virtual ICollection<SOLICITUD__ANTICIPO> SOLICITUD__ANTICIPO { get; set; }
    }
}
