-- NIVELES
INSERT INTO [dbo].[NIVEL]([COD_NIVEL],[NIVEL])VALUES ('PRIMER NIVEL', 1);
INSERT INTO [dbo].[NIVEL]([COD_NIVEL],[NIVEL])VALUES ('SEGUNDO NIVEL', 2);

--CARGOS
INSERT INTO [dbo].[CARGO]([IDNIVEL] ,[NOMCARGO], [ESTCARGO]) VALUES (1 ,'JEFE TÉCNICO DE ÁREA', 1);
INSERT INTO [dbo].[CARGO]([IDNIVEL] ,[NOMCARGO], [ESTCARGO]) VALUES (2 ,'CÓDIGO DE TRABAJO', 1);
INSERT INTO [dbo].[CARGO]([IDNIVEL] ,[NOMCARGO], [ESTCARGO]) VALUES (2 ,'SERVIDOR PÚBLICO 1', 1);
INSERT INTO [dbo].[CARGO]([IDNIVEL] ,[NOMCARGO], [ESTCARGO]) VALUES (2 ,'SERVIDOR PÚBLICO 4', 1);
INSERT INTO [dbo].[CARGO]([IDNIVEL] ,[NOMCARGO], [ESTCARGO]) VALUES (2 ,'SERVIDOR PÚBLICO 7', 1);

--PERFILES
INSERT INTO [dbo].[PERFIL]([NOMBREPERFIL])VALUES('Lider Administrativo');
INSERT INTO [dbo].[PERFIL]([NOMBREPERFIL])VALUES('Asistente Administrativo');
INSERT INTO [dbo].[PERFIL]([NOMBREPERFIL])VALUES('Director Administrativo');
INSERT INTO [dbo].[PERFIL]([NOMBREPERFIL])VALUES('Administrador');

--Menu PerFiles
USE [SIGVIDAPS]
GO

INSERT INTO [dbo].[MENU_PERFIL]([IDPERFIL],[MENUPERFIL])VALUES(1,'mnuAprobarFormularioAnticipo');
INSERT INTO [dbo].[MENU_PERFIL]([IDPERFIL],[MENUPERFIL])VALUES(1,'mnuAprobarFormularioLiquidacion');
INSERT INTO [dbo].[MENU_PERFIL]([IDPERFIL],[MENUPERFIL])VALUES(1,'mnuEmpleados');
INSERT INTO [dbo].[MENU_PERFIL]([IDPERFIL],[MENUPERFIL])VALUES(1,'mnuAdministracion');
INSERT INTO [dbo].[MENU_PERFIL]([IDPERFIL],[MENUPERFIL])VALUES(2,'mnuFormularios');
INSERT INTO [dbo].[MENU_PERFIL]([IDPERFIL],[MENUPERFIL])VALUES(3,'mnuEmpleado');
INSERT INTO [dbo].[MENU_PERFIL]([IDPERFIL],[MENUPERFIL])VALUES(3,'mnuAdministracion');
INSERT INTO [dbo].[MENU_PERFIL]([IDPERFIL],[MENUPERFIL])VALUES(3,'mnuRegistrarFormularioAnticipo');
INSERT INTO [dbo].[MENU_PERFIL]([IDPERFIL],[MENUPERFIL])VALUES(3,'mnuRegistrarFormularioLiquidación');
INSERT INTO [dbo].[MENU_PERFIL]([IDPERFIL],[MENUPERFIL])VALUES(3,'mnuEditarFormularioLiquidación');


--RUTAS
USE [SIGVIDAPS]
GO
INSERT INTO [dbo].[RUTA]([LUGARSALIDA],[LUGARLLEGADA],[CODRUTA], [ESTRUTA]) VALUES ('QUITO' ,'TABABELA','QUI-TAB', 1);
INSERT INTO [dbo].[RUTA]([LUGARSALIDA],[LUGARLLEGADA],[CODRUTA], [ESTRUTA]) VALUES ('TABABELA' ,'QUITO','TAB-QUI', 1);
INSERT INTO [dbo].[RUTA]([LUGARSALIDA],[LUGARLLEGADA],[CODRUTA], [ESTRUTA]) VALUES ('QUITO' ,'LOJA','QUI-LOJ', 1);
GO
