-- NIVELES
INSERT INTO [dbo].[NIVEL]([COD_NIVEL],[NIVEL])VALUES ('PRIMER NIVEL', 1);
INSERT INTO [dbo].[NIVEL]([COD_NIVEL],[NIVEL])VALUES ('SEGUNDO NIVEL', 2);

--CARGOS
INSERT INTO [dbo].[CARGO]([IDNIVEL] ,[NOMCARGO]) VALUES (1 ,'JEFE TÉCNICO DE ÁREA');
INSERT INTO [dbo].[CARGO]([IDNIVEL] ,[NOMCARGO]) VALUES (2 ,'CÓDIGO DE TRABAJO');
INSERT INTO [dbo].[CARGO]([IDNIVEL] ,[NOMCARGO]) VALUES (2 ,'SERVIDOR PÚBLICO 1');
INSERT INTO [dbo].[CARGO]([IDNIVEL] ,[NOMCARGO]) VALUES (2 ,'SERVIDOR PÚBLICO 4');
INSERT INTO [dbo].[CARGO]([IDNIVEL] ,[NOMCARGO]) VALUES (2 ,'SERVIDOR PÚBLICO 7');